# Dry run publish to see if everything is fine in the documentation
name: Publish to README (dry run)

# Execute this pipeline when a push is made to any branch
on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      
      - name: Sync docs to ReadMe (dry run)
        uses: readmeio/rdme@main
        with:
          rdme: openapi ./documentation/wordcab_api_reference.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }} --dryRun
