# Publish the documentation to ReadMe
name: Publish to README

# Execute this pipeline when a push is made to any branch
on:
  push:
    tags:
      - 'v*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      
      - name: Sync docs to ReadMe (dry run)
        uses: readmeio/rdme@main
        with:
          rdme: openapi ./documentation --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }} --dryRun

      - name: Sync docs to ReadMe
        uses: readmeio/rdme@main
        with:
          rdme: openapi ./documentation --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }} --version=${{ github.ref_name }}
