# Publish the documentation to ReadMe
name: Publish to README

# Execute this pipeline when a push is made to any branch
on:
  push:
    tags:
      - 'v*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      # Dynamically update our docs with the latest version of rdme
      - name: Install and build rdme deps
        run: npm ci && npm run build

      - name: Retrieve version values
        id: rdme-version
        run: ./bin/set-version-output

      - name: Find and replace Node.js version placeholders
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'NODE_VERSION'
          replace: ${{ steps.rdme-version.outputs.NODE_VERSION }}
          regex: false
          include: documentation/*

      - name: Find and replace `rdme` version placeholders
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'RDME_VERSION'
          replace: ${{ steps.rdme-version.outputs.RDME_VERSION }}
          regex: false
          include: documentation/*
      
      # Dry run to test everything is fine
      - name: Sync docs to ReadMe (dry run)
        uses: readmeio/rdme@main
        with:
          rdme: openapi ./documentation --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }} --dryRun

      # Publish the documentation to ReadMe
      - name: Sync docs to ReadMe
        uses: readmeio/rdme@main
        with:
          rdme: openapi ./documentation --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }} --version=${{ github.ref_name }}
